server:
  port: 8000
  
spring:
  application:
    name: spring-cloud-eureka
  profiles:
    active: dev
    
eureka: 
  client:
    #禁止自己当做服务注册
    register-with-eureka: false
    #屏蔽注册信息
    fetch-registry: false
    serviceUrl:
      #部署多个注册中心时，这里配置其他配置中心的地址。如：http://localhost:8001/eureka/,http://localhost:8002/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
# log
logging: 
  level: 
    com: 
      netflix: 
        eureka: OFF
        discovery: OFF
  file: ./logs/${spring.application.name}.log

---     
spring: 
  profiles: dev

eureka: 
  instance: 
    hostname: localhost
    ip-address: 127.0.0.1

logging: 
  level: 
    root: INFO
---    
spring: 
  profiles: prod

eureka: 
  instance: 
    hostname: localhost
    ip-address: 127.0.0.1

logging: 
  level: 
    root: WARN
---   


