server:
  port: 8100
  
spring:
  application:
    name: spring-cloud-turbine
  profiles:
    active: prod

eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

# log
logging: 
  level: 
    com: 
      netflix: 
        eureka: OFF
        discovery: OFF
  file: ./logs/${spring.application.name}.log  


---     
spring: 
  profiles: dev
  

  
logging: 
  level: 
    root: INFO
---     
spring: 
  profiles: prod 
  
turbine:
  appConfig: spring-cloud-consumer-admin, spring-cloud-consumer-oauth
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")
  
logging: 
  level: 
    root: WARN  
--- 
