server:
  port: 10000
  
spring:
  application:
    name: spring-cloud-consumer-oauth
  profiles:
    active: prod
    
eureka: 
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${cloud.server.port}/eureka

#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
  
# 认证
auth:
  secret: 212520
  accessTokenValiditySecond: 7200
  refreshTokenValiditySecond: 8640000
  client_id: 4356a818-2fad-499e-8c61-62d33a5735ed
  client_secret: 068v7AgVF057Il5iF3Bz8uW245TW77
 
# log
logging: 
  level: 
    com: 
      netflix: 
        eureka: OFF
        discovery: OFF
  file: ./logs/${spring.application.name}.log     
---     
spring: 
  profiles: dev
        
# cloud
cloud: 
  server: 
    port: 8000 
eureka: 
  instance: 
    # 注册中心地址
    hostname: localhost
    # 服务部署地址
    ip-address: 127.0.0.1

logging: 
  level: 
    root: INFO
    
---     
spring: 
  profiles: prod
  zipkin:
    base-url: http://localhost:8300
  sleuth:
    sampler:
      percentage: 1.0
      
# cloud
cloud: 
  server: 
    port: 8000
eureka: 
  instance: 
    # 注册中心地址
    hostname: localhost
    # 服务部署地址
    ip-address: 127.0.0.1
    
feign: 
  hystrix: 
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
logging: 
  level: 
    root: WARN  
---   


