spring:
    profiles:
        active: dev
---     
spring: 
  application:
    name: spring-cloud-consumer-admin
  profiles: dev
  #zipkin:
    #base-url: http://localhost:8300
  #sleuth:
    #sampler:
      #percentage: 1.0
server:
  port: 9100
  
eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
      
#feign: 
  #hystrix: 
    #enabled: false