server:
  port: 9100
  
spring:
  application:
    name: spring-cloud-consumer-admin
  profiles:
    active: dev
    
eureka: 
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${cloud.server.port}/eureka  
    
# 认证
auth:
  secret: 212520
security: 
  oauth2: 
    resource: 
      token-info-uri: http://${cloud.oauth2.hostname}:${cloud.oauth2.port}/oauth/check_token

swagger: 
  # 公共信息
  enabled: true
  title: 后台管理业务模块
  description: 包含常用基础模块，用户管理、角色管理、权限管理、字典管理等
  version: 1.0
  # 许可证及服务条款信息
  license:
  licenseUrl:
  termsOfServiceUrl:
  contact:
    name: lisz
    url:
    email: 1216535@qq.com
  base-package: cn.com.lisz.consumer.admin.controller
  # 鉴权策略ID，对应 SecurityReferences ID
  authorization: 
    name: Authorization
    # 鉴权传递的Header参数
    key-name: Authorization
      
# log
logging: 
  level: 
    com: 
      netflix: 
        eureka: OFF
        discovery: OFF
  file: ./logs/${spring.application.name}.log   
---     
spring: 
  profiles: dev
  
# cloud
cloud: 
  server: 
    port: 8000
  #认证中心配置
  oauth2: 
    hostname: localhost
    port: 10000
eureka: 
  instance: 
    # 注册中心地址
    hostname: localhost
    # 服务部署地址
    ip-address: 127.0.0.1

logging: 
  level: 
    root: INFO
---     
spring: 
  profiles: prod 
  
# cloud
cloud: 
  server: 
    port: 8000
  #认证中心配置
  oauth2: 
    hostname: localhost
    port: 10000
eureka: 
  instance: 
    # 注册中心地址
    hostname: localhost
    # 服务部署地址
    ip-address: 127.0.0.1
    
logging: 
  level: 
    root: WARN  
--- 
#spring:  
  #zipkin:
    #base-url: http://localhost:8300
  #sleuth:
    #sampler:
      #percentage: 1.0
      
#feign: 
  #hystrix: 
    #enabled: false
  
