server:
  port: 8888
  
spring:
  application:
    name: spring-cloud-zuul
    profiles:
        active: dev
     
eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka

# 构建路由地址
zuul:
  #忽略真实服务名称
  ignored-services: spring-cloud-*
  sensitive-headers: Set-Cookie、Cookie、Host、Connection、Content-Length、Content-Encoding、Server、Transfer-Encoding、X-Application-Context
  routes:
    # 这里可以自定义
    admin:
      # 匹配的路由规则
      path: /admin/**
      # 路由的目标服务名
      serviceId: spring-cloud-consumer-admin
    security:
      # 匹配的路由规则
      path: /oauth/**
      # 路由的目标服务名
      serviceId: spring-cloud-consumer-oauth
  #是否开启重试功能
  retryable: true
#对当前服务的重试次数
ribbon:
  MaxAutoRetries: 2
  #切换相同Server的次数
  MaxAutoRetriesNextServer: 0

# log
logging: 
  level: 
    com: 
      netflix: 
        eureka: OFF
        discovery: OFF
  file: ./logs/${spring.application.name}.log 
--- 
spring: 
  profiles: dev

     
logging: 
  level: 
    root: INFO
---  
spring: 
  profiles: prod
  
   
logging: 
  level: 
    root: WARN 
---
#spring: 
  #zipkin:
    #base-url: http://localhost:8300
  #sleuth:
    #sampler:
      #percentage: 1.0

