spring:
    profiles:
        active: dev
---     
spring: 
  application:
    name: spring-cloud-consumer-oauth
  profiles: dev
  #zipkin:
    #base-url: http://localhost:8300
  #sleuth:
    #sampler:
      #percentage: 1.0
server:
  port: 10000
  
eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
      
#feign: 
  #hystrix: 
    #enabled: false
swagger: 
  base-package: cn.com.lisz.consumer.admin.controller
  
# JWT
jwt:
  header: Authorization
  secret: MallDb52
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"