spring:
    profiles:
        active: dev
---     
spring: 
  application:
    name: spring-cloud-zipkin
  profiles: dev
  
server:
  port: 8300
  
eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
